name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on:
      - self-hosted
      - Linux
      - X64

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Pull latest image
        working-directory: /home/mohammad/projects/flask-docker-cicd
        run: |
          docker compose pull

      - name: Deploy application
        working-directory: /home/mohammad/projects/flask-docker-cicd
        run: |
          docker compose up -d --remove-orphans

      - name: Show running containers
        run: docker ps

      - name: Wait for application
        run: sleep 10

      - name: Health Check
        run: |
          curl --fail http://localhost/health

      - name: Deployment completed
        run: echo "Deployment completed successfully."
